FROM php:7.2-fpm-alpine
LABEL maintainer="malameda@laliga.es"

# Install PHP extensions and PECL modules.
RUN apk add --update \
		icu-dev libjpeg libjpeg-turbo-dev \
		libxml2 libxml2-dev libpng libpng-dev \
		autoconf freetype-dev\
		g++ \
		libtool \
		make \
		
	&& docker-php-ext-install mbstring \
	&& docker-php-ext-install mysqli \
	&& docker-php-ext-install opcache \

    && apk update \
    && docker-php-ext-install intl soap zip xmlrpc\
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd \
    && docker-php-ext-install exif \
    && pecl install apcu \
    && docker-php-ext-enable apcu.so

RUN apk del \
		postgresql-libs \
		libsasl \
		db \

	&& apk del \
		autoconf \
		bash \
		binutils \
		binutils-libs \
		db \
		expat \
		file \
		g++ \
		gcc \
		gdbm \
		gmp \
		isl \
		libatomic \
		libbz2 \
		libc-dev \
		libffi \
		libgcc \
		libgomp \
		libldap \
		libltdl \
		libmagic \
		libsasl \
		libstdc++ \
		libtool \
		m4 \
		make \
		mpc1 \
		mpfr3 \
		musl-dev \
		perl \
		pkgconf \
		pkgconfig \
		python \
		re2c \
		readline \
		sqlite-libs \
		zlib-dev \
	&& rm -rf /tmp/* /var/cache/apk/*